---
apiVersion: v1
offerings:
  - name: terraform-ibm-cos
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 18cdd8f4-40c5-4fbf-9d62-1dd86a2deab3
    examples:
      # TODO: Once support is added to the pipeline to handle code freeze windows, update mark_ready to true
      - name: basic
        mark_ready: false
      - name: advanced
        mark_ready: false
      - name: fscloud
        mark_ready: false
      - name: one-rate-plan
        mark_ready: false
      - name: replication
        mark_ready: false
  - name: deploy-arch-ibm-cos
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 68921490-2778-4930-ac6d-bae7be6cd958
    variations:
      - name: secure
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
