---
apiVersion: v1
offerings:
  - name: terraform-ibm-cos
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 18cdd8f4-40c5-4fbf-9d62-1dd86a2deab3
    examples:
      # TODO: Once support is added to the pipeline to handle code freeze windows, update mark_ready to true
      - name: basic
        mark_ready: false
      - name: advanced
        mark_ready: false
      - name: fscloud
        mark_ready: false
      - name: one-rate-plan
        mark_ready: false
      - name: replication
        mark_ready: false
  - name: deploy-arch-ibm-cos
    kind: solution
    catalog_id: # should be same as catalog_id?
    offering_id: # need to get offering_id using second step in onboarding docs
    variations:
      - name: secure
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: # need to get instance id
          region: us-south # confirm the region to use
