---
apiVersion: v1
offerings:
  - name: terraform-ibm-cos
    kind: module
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 18cdd8f4-40c5-4fbf-9d62-1dd86a2deab3
    examples:
      - name: basic
        mark_ready: true
      - name: advanced
        mark_ready: true
      - name: fscloud
        mark_ready: true
      - name: one-rate-plan
        mark_ready: true
      - name: replication
        mark_ready: true
  - name: deploy-arch-ibm-cos
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 68921490-2778-4930-ac6d-bae7be6cd958
    variations:
      - name: instance
        mark_ready: true
        install_type: fullstack
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
      - name: secure-cross-regional-bucket
        mark_ready: true
        install_type: extension
        pre_validation: "tests/scripts/pre-validation-deploy-cos-cross-region.sh"
        post_validation: "tests/scripts/post-validation-deploy-cos-cross-region.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
      - name: secure-regional-bucket
        mark_ready: true
        install_type: extension
        pre_validation: "tests/scripts/pre-validation-deploy-cos-regional.sh"
        post_validation: "tests/scripts/post-validation-deploy-cos-regional.sh"
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
