name: Release-Pipeline

# Trigger on push(merge) to main branch
on:
  push:
    branches:
      - main

jobs:
  call-terraform-release-pipeline:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: terraform-ibm-modules/common-pipeline-assets/.github/workflows/common-release.yml@v1.12.0
    secrets: inherit
