name: Verify

on:
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        if $(curl https://github.com/terraform-ibm-modules/terraform-ibm-cos/actions/workflows/ci.yml/badge.svg | grep "<title>CI-Pipeline - passing</title>"); then
          exit 0
        else
          exit 1
        fi

  verifyMetadata:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-module-metadata.yaml@v1
