name: Verify

on:
 workflow_run:
    workflows: ["CI-Pipeline"]
    branches: [main]
    types:
      - completed
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      CONCLUSION: ${{ github.event.workflow_run.conclusion }}
    steps:
    - shell: bash
      run: |
        if [[ "$CONCLUSION" == "success" ]]; then
          exit 0
        else
          exit 1
        fi

  verifyMetadata:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-module-metadata.yaml@v1
