name: Verify

# Trigger on push(merge) to main branch
on:
  push:
    branches:
      - main
jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - shell: bash
      run: |
        echo "Verified"

  verifyMetadata:
    uses: cloud-native-toolkit/action-workflows/.github/workflows/verify-module-metadata.yaml@v1
